export const FETCH_PURCHASES_REQUEST = 'FETCH_PURCHASES_REQUEST';
export const FETCH_PURCHASES_SUCCESS = 'FETCH_PURCHASES_SUCCESS';
export const FETCH_PURCHASES_FAILURE = 'FETCH_PURCHASES_FAILURE';

export const CHANGE_EDIT_AMOUNT = 'CHANGE_EDIT_AMOUNT';
export const CHANGE_EDIT_CATEGORY = 'CHANGE_EDIT_CATEGORY';
export const CHANGE_EDIT_DESCRIPTION = 'CHANGE_EDIT_DESCRIPTION';

export const FETCH_PURCHASE_DESCRIPTION_REQUEST = 'FETCH_PURCHASE_DESCRIPTION_REQUEST';
export const FETCH_PURCHASE_DESCRIPTION_SUCCESS = 'FETCH_PURCHASE_DESCRIPTION_SUCCESS';

export const TOGGLE_OPEN = 'TOGGLE_OPEN';

export const EDIT_PURCHASE = 'EDIT_PURCHASE';
export const RESET_PURCHASE = 'RESET_PURCHASE';